version: '3.4'

services:
  go:
    build: ./docker/golang/
    environment:
      - PROXY_URL
      - PROXY_PORT
    volumes:
      - ./docker/golang:/go/src/hot_reload_docker
    ports:
      - "18080-18083:8080-8083"
    networks:
      - default
      - external
  iptables:
    build: ./docker/iptables/
    environment:
      - PROXY_PORT
    volumes:
      - ./docker/iptables/scripts:/etc/scripts
    command: sh /etc/scripts/init-iptables.sh
    tty: true
    network_mode: "container:${CONTAINER_NAME:-}"
    cap_add:
      - NET_ADMIN

networks:
  default:
    driver: bridge
  external:
    external:
      name: ${NETWORK_NAME:-request-catcher-2_default}
